### ISSUE TITLE
Consume street info from Google Doc

### ISSUE THREAD

**Issue by despinoUY** [datauy/a-tu-nombre#3]
The plan is to consume the street info from a Google Sheet and display it in the site.

**Comment by EmilioCristalli** [comment]
@despinoUY what do you mean by street info?

**Comment by despinoUY** [comment]
I mean by this the description of the woman naming each street.

**Comment by n370** [comment]
If you guys want to keep the data dynamic you can try these libraries:

- https://github.com/jadeallencook/gDoc.js
- https://github.com/FranciscoP/drive-db
