### ISSUE TITLE
Información de la Comisión de Nomenclatura de la Junta Departamental desactualizada

### ISSUE THREAD

**Issue by ismaelpadilla** [datauy/a-tu-nombre#7]
En la [página de proyecto](https://atunombre.uy/proyecto.html), la siguiente información de la  Comisión de Nomenclatura de la Junta Departamental está desactualizada:

- Link: el link que está no anda, probablemente debería ser https://www.gub.uy/junta-departamental-montevideo/politicas-y-gestion/comision-nomenclatura
- Nombre del presidente: debería ser Gustavo Zúñiga.

Ver pull request: #6

**Comment by danielcarranza** [comment]
¡Muchas gracias! Aprobamos el pull request y subimos actualizado 💪
